config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  devise_for :users
  resources :users, only: [:show] 
  resources :shops do
    resources :likes, only: [:create, :destroy]
    resources :comments, only: [:create]
  end
  resources :relationships, only: [:create, :destroy]
  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show]
  root "shops#index"

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :shop
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :shop
  belongs_to :user

  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/shop.rb
class Shop < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
    has_many :shop_tag_relations, dependent: :destroy
    has_many :tags, through: :shop_tag_relations, dependent: :destroy
end

app/models/shop_tag_relation.rb
class ShopTagRelation < ApplicationRecord
  belongs_to :shop
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    validates :name, presence: true
    has_many :shop_tag_relations, dependent: :destroy
    has_many :shops, through: :shop_tag_relations, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_shops, through: :likes, source: :shop
  has_many :comments, dependent: :destroy
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 } 

  def already_liked?(shop)
    self.likes.exists?(shop_id: shop.id)
  end
  
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        like = current_user.likes.create(shop_id: params[:shop_id]) 
        redirect_back(fallback_location: root_path)
    end

    def destroy
        like = Like.find_by(shop_id: params[:shop_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    Entry.create(room_id: @room.id, user_id: current_user.id)
    Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages.all
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
    before_action :authenticate_user!, only: [:new, :create]

    def index
        if params[:search] != nil && params[:search] != ''
        search = params[:search]
        @shops = Shop.where("place LIKE ? OR shop_name LIKE ? OR adress LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%").page(params[:page]).per(6)
      else
        @shops = Shop.all.page(params[:page]).per(6)
      end
      @tag = Tag.select("name", "id")
      tag_search = params[:tag_search]
      if tag_search != nil
          @shops = Tag.find_by(id: tag_search).shops
      else
          @shops = Shop.all
      end
      @shops = Kaminari.paginate_array(@shops).page(params[:page]).per(6)
    end

    def new
        @shop = Shop.new
    end

    def create
        shop = Shop.new(shop_params)
        shop.user_id = current_user.id  
        if shop.save!
            redirect_to :action => "index"
        else
            redirect_to :action => "new"
        end
    end

    def show
        @shop = Shop.find(params[:id])
        @comments = @shop.comments
        @comment = Comment.new
    end
    
    def edit
        @shop = Shop.find(params[:id])
    end

    def update
        shop = Shop.find(params[:id])
        if shop.update(shop_params)
          redirect_to :action => "show", :id => shop.id
        else
          redirect_to :action => "new"
        end
      end

    def destroy
        shop = Shop.find(params[:id])
        shop.destroy
        redirect_to action: :index
    end

    private
    def shop_params
        params.require(:shop).permit(:place, :shop_name, :adress, :image, :rating, tag_ids: [])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, :only => [:show]
    def index
      @users=User.all
    end
  
    def show
        @user=User.find(params[:id])
        @currentUserEntry=Entry.where(user_id: current_user.id)
        @userEntry=Entry.where(user_id: @user.id)
        if @user.id == current_user.id
          @msg ="他のユーザーとDMしてみよう！"
        else
          @currentUserEntry.each do |cu|
            @userEntry.each do |u|
              if cu.room_id == u.room_id then
                @isRoom = true
                @roomId = cu.room_id
              end
            end
          end
    
          if @isRoom != true
            @room = Room.new
            @entry = Entry.new
          end
    
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper

    def getPercent(number) 
        if number.present?
          calPercent = number/5.to_f * 100
          # calPercent = number/10.to_f * 100
          #↑１０段階評価の際は2行目コメントアウトを外して、1行目をコメントアウト。
          percent = calPercent.round
          #↑CSSは小数が含まれると、widthの幅を指定できないので四捨五入して整数化。
          return percent.to_s
        else
          return 0
        end
      end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/show.html.erb
<h1>Rooms#show</h1>
<p>Find me in app/views/rooms/show.html.erb</p>
<div class="user-in">
<% @entries.each do |e| %>
    <h3><strong><a href="/users/<%= e.user.id %>"><%= e.user.email%></a></strong></h3>
<% end %>
<p>2人のDM❤️</p>
</div>

<div class="dmMain">
    <% @messages.each do |m| %>
        <strong><%= m.body %></strong>
        <small><%= m.user.email %>さん</small><hr>
    <% end %>

    <%= form_for @message do |f| %>
    <%= f.text_field :body, :placeholder => "メッセージを入力して下さい" , :size => 100 %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信する" %>
    <% end %>
</div>

<%= link_to "ユーザー一覧に戻る", user_path %>


<style>
.user-in{
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
}
.dmMain{
    padding:30px;
    border:1px solid darkgray;
    background-color:gainsboro;
}
</style>

app/views/shops/edit.html.erb
<%= form_for @shop do |f| %>
  <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :店名 %>
    <%= f.text_field :shop_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :adress, :size => 30 %>
  </div>
    <%= f.submit "編集する" %>
  <% end %>

app/views/shops/index.html.erb
<h1>GeekCafe</h1>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"shops",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<%= form_tag({controller:"shops",action:"index"}, method: :get) do %>
  <%= select_tag :tag_search, options_from_collection_for_select(@tag, "id","name") %>
  <%= submit_tag '検索' %>
<% end %>

<h3>一覧ページ</h3>
<%= link_to "新規投稿へ", new_shop_path %>

<% if user_signed_in? %>
  <%= link_to "マイページへ", user_path(current_user.id) %>
<% end %>

<%= page_entries_info @shops %>
<div class="shops-container">
  <% @shops.each do |t| %>
    <div class="shop">
    <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
      <%= t.place %>
      <%= t.shop_name %>
      <%= t.adress %>
      <%= image_tag t.image_url, size: "250x200" if t.image? %>
      <div>
        <h2>総合評価：
        <span class="star-rating">
          <span class="star-rating-front" style="width: <%= getPercent(t.rating) %>%;">★★★★★</span>
          <span class="star-rating-back">★★★★★</span>
        </span> 
        </h2>
      </div>
      <% if user_signed_in? %>
      <% if current_user.already_liked?(t) %>
          <%= button_to shop_like_path(id: t.id, shop_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
          <% end %>
      <% else %>
          <%= button_to shop_likes_path(id: t.id, shop_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
          <% end %>
      <% end %>
  <% else %>
      <p>いいねの数 = </p><%= t.likes.count %>
  <% end %>
      <%= link_to "詳細へ", shop_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %> 
        <%= link_to "編集する", edit_shop_path(t.id) %>
        <%= button_to "削除する", shop_path(t.id), method: :delete %>
      <% end %>
    </div>
  <% end %>
</div>
<%= paginate @shops %>

app/views/shops/new.html.erb
<h1>GeekCafe</h1>
<h3>新規投稿ページ</h3>
<%= form_for @shop do |f| %>

  <div class="field">
    <%= f.label :場所 %>
    <%= f.text_field :place, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :店名 %>
    <%= f.text_field :shop_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :住所 %>
    <%= f.text_field :adress, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image %>
  </div>

  <div class='form-group'>
        <%= f.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
            <div class='form-check'>
                <%= tag.label class: 'form-check-label' do %>
                    <%= tag.check_box class: 'form-check-input' %>
                    <%= tag.text %>
                <% end %>
            </div>
        <% end %>
    </div>

  <h5>総合評価</h5>
    <div class="post_form">
     <%= f.radio_button :rating, 5 ,id: 'star1'%>
     <label for="star1"><span class="text">最高</span>★</label>
 
     <%= f.radio_button :rating, 4 ,id: 'star2'%>
     <label for="star2"><span class="text">良い</span>★</label>
 
     <%= f.radio_button :rating, 3 ,id: 'star3'%>
     <label for="star3"><span class="text">普通</span>★</label>
 
     <%= f.radio_button :rating, 2 ,id: 'star4'%>
     <label for="star4"><span class="text">悪い</span>★</label>
 
     <%= f.radio_button :rating, 1 ,id: 'star5'%>
     <label for="star5"><span class="text">最悪</span>★</label>
  </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", shops_path %>

app/views/shops/show.html.erb
<h1>GeekCafe</h1>
<h3>詳細</h3>
<div class="shop">
  <p><%= @shop.place %></p>
  <p><%= @shop.shop_name %></p>
  <p><%= @shop.adress %></p>
  <p><%= @shop.created_at %></p>
    <% if user_signed_in? %>
        <% if current_user.already_liked?(@shop) %>
            <%= button_to shop_like_path(@shop), method: :delete do %>
                <p>いいねを取り消す</p><%= @shop.likes.count %>
            <% end %>
        <% else %>
            <%= button_to shop_likes_path(@shop), method: :post do %>
                <p>いいね</p><%= @shop.likes.count %>
            <% end %>
        <% end %>
    <% else %>
        <p>いいねの数 = </p><%= @shop.likes.count %>
    <% end %>
      <%= link_to "編集する", edit_shop_path(@shop.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @shop.liked_users.each do |user| %>
    <li><%= user.email %></li>
<% end %>

<% @shop.tags.each do |tag| %>
  <span><%= tag.name %></span>
<% end %>

<div class="comment-wrapper">
  <p>コメント一覧</p>
  <% @comments.each do |c| %>
    <div>
      <%= c.user.email unless c.user.blank? %>
      <br>
      <%= c.content %>
    </div>
      <br>
  <% end %>

  <% if user_signed_in? %>
    <%= form_with(model: [@shop, @comment], local: true) do |f| %>
      <%= f.text_area :content %>
      <%= button_tag type: "submit" do %>
        <i class="far fa-comments"></i> コメントする
      <% end %>
    <% end %>
  <% end %>
</div>

<%= link_to "一覧に戻る", shops_path %>

app/views/users/index.html.erb
<h1>DMサンプル</h1>
<h2>User一覧ページ</h2>

<% if user_signed_in? %>
    <h2><%= current_user.email %>でログインしています</h2> 
    <%= link_to "SignOut", destroy_user_session_path, :method => :delete, class:"signOutButton" %>


    <% number = 1%>
    <div class="flex">
        <% @users.each do |u| %>
        <div class="user-in">
            <p>プロフィール No.<%= number %></p>
            <p><%= u.email %>さん</p>
            <p><%= link_to 'ユーザーページへ', user_path(u.id) %></p>
        </div>
        <% number += 1 %>
        <% end %>
    </div>

<% else %>
  <%= link_to "SignUp", new_user_registration_path %>
  <br>
  <%= link_to "SignIn", new_user_session_path %>
<% end %>

<style>
.signOutButton{
    text-decoration:none;
    display:inline-block;
    border:3px solid royalblue;
    background-color:aliceblue;
    padding:5px;
}
.flex{
    display:flex;
    flex-wrap:wrap;    
}
.user-in{
    display:block;
    width:300px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
    flex-shrink: 0;
}
</style>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>users#show</h1>
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.shops.each do |t| %>
  <%= t.place %>
  <%= t.shop_name %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_shops.each do |t| %>
  <%= t.user.name %>
  <%= t.shop_name %>
<% end %>
<!-- ここまで-->

<div class="user-in">
<h2><%= @user.email %></h2>

<% if @user.id == current_user.id %>
    <%= @msg %>
<% else %>
    <% if @isRoom == true %>
        <p><%= link_to 'DMへ', room_path(@roomId) %></p>
    <% else %>
        <%= form_for @room do |f| %>
            <%= fields_for @entry do |e|%>
                <% e.hidden_field :user_id, value: @user.id %>
            <% end %>
        <%= f.submit "DMを開始する"%>
        <% end %>
    <% end %>
<% end %>
</div>

<%= link_to "一覧に戻る", shops_path %>

<style>
.user-in{
    width:300px;
    padding:10px;
    margin:10px;
    text-align:center;
    border:1px solid darkgray;
    background-color:gainsboro;
}
</style>